title: LGPD - Segurança de dados, sanções e multas
remote_theme: just-the-docs/just-the-docs
aux_links:
  Código-fonte no GitHub: https://github.com/maariaceciliaholler/ecs.github.io
footer_content: "© 2025 • Manual LGPD – Segurança de dados, sanções e multas"

sass:
  style: compressed

just_the_docs:
  stylesheets:
    - /assets/css/custom.scss